# Generated by Django 6.0.4 on 2026-04-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('peso', models.FloatField(help_text='Peso em kg')),
                ('alt', models.FloatField(help_text='Altura em metros')),
                ('larg', models.FloatField(help_text='Largura em metros')),
                ('comp', models.FloatField(help_text='Comprimento em metros')),
                ('val', models.FloatField(help_text='Valor em R$')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cap_peso', models.FloatField(help_text='Capacidade de peso em kg')),
                ('alt', models.FloatField(help_text='Altura em metros')),
                ('larg', models.FloatField(help_text='Largura em metros')),
                ('comp', models.FloatField(help_text='Comprimento em metros')),
            ],
        ),
    ]
