# Generated by Django 6.0.4 on 2026-04-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade desta carga'),
        ),
    ]
